import type { Metadata } from 'next'
import Home from '@/screens/Home'

// Server Component on purpose — metadata exports aren't allowed from a
// 'use client' file, and this used to be one (Home/Feed/Discover carry their
// own 'use client' directives so they don't need to inherit the boundary from
// here). Providers still renders nothing until mount, so this only fixes the
// <title>/description/OG tags, not full SSR of the home content — providers.tsx's
// own comment already flags that as a separate follow-up.
const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || 'https://shelf.nonsapp.com').replace(/\/+$/, '')
// The shared social card (public/img/og.png, generated by scripts/generate-og.mjs).
// Absolute so it resolves without a metadataBase, matching nons-client.
const OG_IMAGE = `${SITE_URL}/img/og.png`

export const metadata: Metadata = {
  title: 'Nons Shelf — Every Book and Film You Love, on One Shelf',
  description:
    'Track what you read and watch, rate it, and see what your friends on nons are into — one shelf for books and films instead of switching between Goodreads and Letterboxd.',
  keywords: [
    'Nons Shelf',
    'book and film tracker',
    'book and movie tracker',
    'shelf for books and movies',
    'Goodreads and Letterboxd alternative',
    'track what you read and watch',
    'movie and book ratings with friends',
    'shared media catalog',
    'no ads no tracking media tracker',
  ],
  openGraph: {
    type: 'website',
    url: SITE_URL,
    title: 'Nons Shelf — Every Book and Film You Love, on One Shelf',
    description:
      'Track what you read and watch, rate it, and see what your friends on nons are into — without the noise.',
    siteName: 'Nons Shelf',
    locale: 'en_US',
    images: [
      {
        url: OG_IMAGE,
        width: 1200,
        height: 630,
        alt: 'Shelf — Your books and films, all in one shelf.',
        type: 'image/png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Nons Shelf — Every Book and Film You Love, on One Shelf',
    description:
      'Track what you read and watch, rate it, and see what your friends on nons are into — without the noise.',
    images: [{ url: OG_IMAGE, alt: 'Shelf — Your books and films, all in one shelf.' }],
  },
  alternates: {
    canonical: SITE_URL,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
}

export default function Page() {
  return <Home />
}
